# Generated by Django 3.0.3 on 2020-02-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='case',
        ),
        migrations.AddField(
            model_name='tracker',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='kainos_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='module',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='scenario',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='last_modified',
            field=models.DateTimeField(null=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='result',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tester',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
