# Generated by Django 3.0.3 on 2020-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0003_auto_20200209_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='module',
            field=models.CharField(max_length=100, null=True, verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
