# Generated by Django 3.0.3 on 2020-02-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0005_auto_20200209_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='result',
            field=models.CharField(choices=[('Pass', True), ('Fail', False)], max_length=10, null=True, verbose_name='Result'),
        ),
    ]
