# Generated by Django 3.0.3 on 2020-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0006_auto_20200209_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='session_id',
            field=models.CharField(max_length=250, null=True, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='result',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True, verbose_name='Result'),
        ),
    ]
