# Generated by Django 3.0.3 on 2020-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0007_auto_20200211_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='session_id',
        ),
        migrations.AddField(
            model_name='tracker',
            name='uuid',
            field=models.CharField(max_length=1000, null=True, verbose_name='uuid'),
        ),
    ]
