# Generated by Django 3.0.3 on 2020-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0008_auto_20200223_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='file_name',
            field=models.CharField(max_length=100, null=True, verbose_name='File Name'),
        ),
    ]
