# Generated by Django 3.0.3 on 2020-03-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0009_tracker_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='file_name',
        ),
        migrations.AddField(
            model_name='tracker',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='Category'),
        ),
    ]
