# Generated by Django 2.2.11 on 2020-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_cases', '0010_auto_20200310_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='kainos_id',
        ),
        migrations.AddField(
            model_name='tracker',
            name='case_id',
            field=models.CharField(max_length=200, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='result',
            field=models.CharField(choices=[('None', 'None'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True, verbose_name='Result'),
        ),
    ]
